email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "@nnnnnathan"
tagline: ""
description: "Follow <a href=\"https://micro.blog/nnnnnathan\">@nnnnnathan on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/nnnnnathan\">@nnnnnathan on Micro.blog</a>."
baseurl: ""
url: "http://status.yergler.net"
markdown: "kramdown"
username: "nnnnnathan"
microblog_user: "nnnnnathan"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "@nnnnnathan"
name: "@nnnnnathan"
gravatar_hash: "75dc81420807523b4bdd266160b92e84"
avatar: "https://micro.blog/nnnnnathan/avatar.jpg"
full_name: "@nnnnnathan"
bio: ""
twitter_username: "nyergler"
github_username: "nyergler"
instagram_username: "nyergler"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "1295"
gems: ["jekyll-paginate"]
itunes_description: "Engineer, print maker, aspiring sewcialist. Currently writing code at Lob; formerly CC, Eventbrite, Remind, Plangrid."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Nathan"
itunes_email: ""
podcast: false